### ISSUE TITLE
The 'polling_interval' option is deprecated, please remove it from your configuration

### ISSUE THREAD

**Issue by nmisha** [alryaz/hass-pandora-cas#6] opened 2021-10-12 19:31 UTC
I got message: The 'polling_interval' option is deprecated, please remove it from your configuration
How can I remove the option?

**Comment by denisapokin** [comment] 2021-10-14 19:51
Hi! I got 2 messages:
The 'polling_interval' option is deprecated, please remove it from your configuration
The 'user_agent' option is deprecated, please remove it from your configuration
On core-2021.10.4
After update Pandora CAS object not available.

**Comment by alryaz** [comment] 2021-10-17 06:49
The issue is being worked on, please await an update.

@denisapokin objects being unavailable may signal of some other issue. Please, contact me via Telegram: @alryaz.

**Comment by alryaz** [comment] 2021-10-26 05:54
Fixed in v1.1.0

**Closed as completed by alryaz** 2021-10-26 05:54 UTC
